apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "helm-chart.fullname" . }}-registry
  namespace: {{ .Release.Namespace }}
spec:
  mount: {{ .Values.vault.mount }}
  type: kv-v2
  path: harbor-system/harbor-registry
  refreshAfter: 1h
  destination:
    create: true
    name: {{ include "helm-chart.fullname" . }}-registry
    labels:
      app.kubernetes.io/part-of: argocd
    type: kubernetes.io/dockerconfigjson
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ include "helm-chart.fullname" . }}
