replicaCount: 1

fullnameOverride: spark-frontend

image:
  repository: harbor.infra.sprk.fi/sprk/spark-frontend
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2

serviceAccount:
  create: true
  name: ""
  automount: true

ingress:
  enabled: false
  className: cilium
  annotations:
    kubernetes.io/tls-acme: "true"

resources:
  requests:
    cpu: 1
    memory: 512Mi
