replicaCount: 1

fullnameOverride: spark-frontend

image:
  repository: harbor.infra.v12.trade/sprk/spark-frontend
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2

serviceAccount:
  create: true
  name: ""
  automount: true

ingress:
  enabled: false
  className: cilium
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/custom-headers: spark-frontend/ingress-nginx-custom-headers

resources:
  requests:
    cpu: 100m
    memory: 512Mi
