replicaCount: 1

fullnameOverride: spark-frontend

image:
  repository: harbor.infra.v12.trade/sprk/spark-frontend
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2

serviceAccount:
  create: true
  name: ""
  automount: true

ingress:
  enabled: false
  className: cilium
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.intercomcdn.com https://www.googletagmanager.com https://cdn.jsdelivr.net https://widget.intercom.io; script-src-elem 'self' 'unsafe-inline' 'unsafe-eval' https://js.intercomcdn.com https://www.googletagmanager.com https://cdn.jsdelivr.net https://widget.intercom.io https://s3.tradingview.com; style-src 'self' 'unsafe-inline'; style-src-elem 'self' 'https://fonts.googleapis.com'; connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com https://nexus-websocket-a.intercom.io https://api-iam.intercom.io https://api.bako.global/socket.io wss://api.bako.global/socket.io https://testnet.fuel.network https://mainnet.fuel.network https://relay.walletconnect.org wss://relay.walletconnect.org https://hermes.pyth.network https://indexer.hyperindex.xyz wss://indexer.hyperindex.xyz https://app.sentio.xyz https://api.web3modal.org wss://relay.walletconnect.com https://api.bako.global https://unleash.v12.trade wss://nexus-websocket-a.intercom.io; img-src 'self' data:; font-src 'self' https://fonts.gstatic.com data:; frame-src 'self' https://widgetbot.io https://intercom.io https://widget.intercom.io https://verify.walletconnect.com; media-src 'self'; manifest-src 'self'; worker-src 'self'; child-src 'self'; block-all-mixed-content; upgrade-insecure-requests;";

resources:
  requests:
    cpu: 1
    memory: 512Mi

