replicaCount: 1

fullnameOverride: spark-frontend

image:
  repository: harbor.infra.v12.trade/sprk/spark-frontend
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2

serviceAccount:
  create: true
  name: ""
  automount: true

ingress:
  enabled: false
  className: cilium
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Content-Security-Policy: default-src 'self'; script-src 'self'; object-src 'none'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; font-src 'self'; frame-src 'self'; media-src 'self'; manifest-src 'self'; worker-src 'self'; prefetch-src 'self'; child-src 'self'; block-all-mixed-content; upgrade-insecure-requests; reflected-xss block; referrer no-referrer; feature-policy 'none';";

resources:
  requests:
    cpu: 1
    memory: 512Mi
