replicaCount: 1

fullnameOverride: spark-frontend

image:
  repository: harbor.infra.v12.trade/sprk/spark-frontend
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2

serviceAccount:
  create: true
  name: ""
  automount: true

ingress:
  enabled: false
  className: cilium
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval' https://www.googletagmanager.com https://cdn.jsdelivr.net https://widget.intercom.io; object-src 'none'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://static.intercomassets.com; connect-src 'self' https://www.google-analytics.com https://nexus-websocket-a.intercom.io https://api-iam.intercom.io https://api.bako.global/socket.io https://testnet.fuel.network; font-src 'self' https://fonts.gstatic.com data:; frame-src 'self' https://widgetbot.io https://intercom.io https://widget.intercom.io; media-src 'self'; manifest-src 'self'; worker-src 'self'; child-src 'self'; block-all-mixed-content; upgrade-insecure-requests;";

resources:
  requests:
    cpu: 1
    memory: 512Mi
