name: Cloudflare Pages Deploy

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
jobs:
  deploy:
    permissions:
      actions: read # Only required for private GitHub Repo
      contents: read
      deployments: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@v4
      - name: 'Deploy to Cloudflare Pages'
        uses: andykenward/github-actions-cloudflare-pages@v2.3.1
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-project-name: spark-frontend
          directory: build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-environment: ${{ (github.ref == 'refs/heads/main' && 'production') || 'preview' }}
